// EO: NUL(Paradigm → Paradigm, Clearing) — frozen grammar matrix
// GENERATED by scripts/learn-grammar.mjs — do not edit by hand.
//
// The frozen move-grammar: a bigram transition matrix over the move alphabet,
// learned once from held-out text (data/metamorphosis.txt) so it never sees the reading
// it predicts. Regenerate with `node scripts/learn-grammar.mjs`.

export const DEFAULT_GRAMMAR = Object.freeze({
  alphabet: ["NUL","SEG","DEF","SIG","CON","EVA","INS","SYN","REC","VOID"],
  trans: {
    NUL: { NUL: 0.1, SEG: 0.1, DEF: 0.1, SIG: 0.1, CON: 0.1, EVA: 0.1, INS: 0.1, SYN: 0.1, REC: 0.1, VOID: 0.1 },
    SEG: { NUL: 0.033333, SEG: 0.033333, DEF: 0.033333, SIG: 0.066667, CON: 0.666667, EVA: 0.033333, INS: 0.033333, SYN: 0.033333, REC: 0.033333, VOID: 0.033333 },
    DEF: { NUL: 0.0625, SEG: 0.125, DEF: 0.0625, SIG: 0.0625, CON: 0.0625, EVA: 0.25, INS: 0.1875, SYN: 0.0625, REC: 0.0625, VOID: 0.0625 },
    SIG: { NUL: 0.090909, SEG: 0.090909, DEF: 0.090909, SIG: 0.090909, CON: 0.090909, EVA: 0.181818, INS: 0.090909, SYN: 0.090909, REC: 0.090909, VOID: 0.090909 },
    CON: { NUL: 0.032258, SEG: 0.064516, DEF: 0.064516, SIG: 0.032258, CON: 0.064516, EVA: 0.612903, INS: 0.032258, SYN: 0.032258, REC: 0.032258, VOID: 0.032258 },
    EVA: { NUL: 0.020833, SEG: 0.041667, DEF: 0.020833, SIG: 0.020833, CON: 0.020833, EVA: 0.166667, INS: 0.5625, SYN: 0.020833, REC: 0.104167, VOID: 0.020833 },
    INS: { NUL: 0.023256, SEG: 0.418605, DEF: 0.023256, SIG: 0.023256, CON: 0.046512, EVA: 0.255814, INS: 0.116279, SYN: 0.046512, REC: 0.023256, VOID: 0.023256 },
    SYN: { NUL: 0.090909, SEG: 0.090909, DEF: 0.181818, SIG: 0.090909, CON: 0.090909, EVA: 0.090909, INS: 0.090909, SYN: 0.090909, REC: 0.090909, VOID: 0.090909 },
    REC: { NUL: 0.071429, SEG: 0.071429, DEF: 0.357143, SIG: 0.071429, CON: 0.071429, EVA: 0.071429, INS: 0.071429, SYN: 0.071429, REC: 0.071429, VOID: 0.071429 },
    VOID: { NUL: 0.1, SEG: 0.1, DEF: 0.1, SIG: 0.1, CON: 0.1, EVA: 0.1, INS: 0.1, SYN: 0.1, REC: 0.1, VOID: 0.1 }
  },
  marginal: { NUL: 0.007407, SEG: 0.155556, DEF: 0.051852, SIG: 0.014815, CON: 0.162963, EVA: 0.296296, INS: 0.251852, SYN: 0.014815, REC: 0.037037, VOID: 0.007407 },
  source: "data/metamorphosis.txt",
});
