// EO: REC·SIG(Field,Paradigm → Paradigm,Atmosphere, Composing,Tending) — learned move-grammar
// The small, learned-once move-grammar — the realization grammar for moves.
//
// The operator grammar has regularities of its own: the helix order, the triads,
// the canonical cycles, which moves can follow which. This is the only LEARNED
// component of the predictor, and it is bounded by the size of the operator
// grammar — a transition matrix over ten symbols, learned ONCE from observed
// move-sequences on a held-out text and frozen (data → src/predict/grammar-data.js,
// regenerated by scripts/learn-grammar.mjs). It is not fit per query and needs no
// ingested corpus: ten symbols, one small matrix.
//
// Kept distinct from the recurrence prior on purpose. Recurrence is fit ONLINE from
// THIS reading's log so it adapts to this text; the grammar is the cross-text prior
// the local counts lack, especially early when the log is short. Their product,
// with the structural prior, is the posterior.

import { DEFAULT_GRAMMAR } from './grammar-data.js';

export { DEFAULT_GRAMMAR };

// Fit a bigram move-grammar from an array of move-logs (each an array of moves with
// an `.op`). Add-α smoothed so every transition keeps a floor. Returns a frozen
// matrix { alphabet, trans: prev→next→p, marginal: op→p } — exactly what
// grammar-data.js stores and grammarPrior reads.
export const learnGrammar = (moveLogs, alphabet, { alpha = 1 } = {}) => {
  const inAlpha = new Set(alphabet);
  const uni = Object.fromEntries(alphabet.map(op => [op, 0]));
  const trans = {};                                  // prev → next → count

  for (const moves of moveLogs) {
    let prev = null;
    for (const m of moves) {
      const op = m.op;
      if (!inAlpha.has(op)) continue;
      uni[op] += 1;
      if (prev != null) {
        (trans[prev] ||= {});
        trans[prev][op] = (trans[prev][op] || 0) + 1;
      }
      prev = op;
    }
  }

  const V = alphabet.length;
  const P = {};
  for (const prev of alphabet) {
    const row = trans[prev] || {};
    const ctxN = alphabet.reduce((s, op) => s + (row[op] || 0), 0);
    P[prev] = {};
    for (const op of alphabet) P[prev][op] = round(((row[op] || 0) + alpha) / (ctxN + alpha * V));
  }
  const Nuni = alphabet.reduce((s, op) => s + uni[op], 0);
  const marginal = {};
  for (const op of alphabet) marginal[op] = round((uni[op] + alpha) / (Nuni + alpha * V));

  return { alphabet: [...alphabet], trans: P, marginal };
};

// The grammar's distribution over the next move given the last move's op. Backs off
// to the grammar's marginal when the context row is missing. Always normalised over
// the alphabet.
export const grammarPrior = (lastOp, grammar, alphabet) => {
  const g = grammar || DEFAULT_GRAMMAR;
  const row = (lastOp != null && g.trans && g.trans[lastOp]) ? g.trans[lastOp] : g.marginal;
  const dist = {};
  let Z = 0;
  for (const op of alphabet) {
    const p = row?.[op] ?? g.marginal?.[op] ?? 1 / alphabet.length;
    dist[op] = p;
    Z += p;
  }
  for (const op of alphabet) dist[op] = Z > 0 ? dist[op] / Z : 1 / alphabet.length;
  return dist;
};

const round = (x) => Math.round(x * 1e6) / 1e6;
