// EO: DEF·EVA·INS(Entity,Field → Field,Lens, Making,Binding) — referring generation; inverse coref + the self line
// Writing is reading backwards — referring expression generation as inverse coref.
//
// The reader does not pick an antecedent for "he"; a pronoun induces a FIELD over the
// candidates in play, γ-weighted by reading distance, gated by gender/role compatibility
// (perceiver/parse/coref.js). The strongest candidate wins. WRITING runs that backwards:
// to refer to entity E, emit the surface form the reader's field will resolve BACK to E —
// a pronoun only when E is the unambiguous, sufficiently-active, gender-compatible top of
// the field; otherwise the name. So the writer must maintain a model of the READER's
// field — theory of mind, a separate thread from what the writer means — and choose the
// form that lands the reader on the intended referent. The rules that constrain reading
// (activation/γ-recency, gender conformance, distinctness) are exactly the constraints on
// writing, run in reverse.
//
// ME-NESS (core/provenance.js). Content read FROM THE GIVEN arrives through the PERCEIVER
// door — exafference, unauthored, it can witness but is not mine. Content the writer
// GENERATES arrives through the ENACTOR door — reafference, mine, it cannot witness. When
// the writer reads its own output back (reenter through the perceiver door) it is
// recognised as READ_BACK-of-prior-self — still mine. That reafference loop — author,
// read back, recognise as mine — is what produces the self: a self/world line the given
// graph, however rich, never has, because the given was authored by no one here.

import { fromEnactor, fromPerceiver, reenter, isMine, isReadBackOfPriorSelf, canWitness } from '../../core/index.js';
import { createRule } from './eva.js';
import { toPast } from './morph.js';

const PRONOUN = Object.freeze({
  m: { subj: 'he', obj: 'him', poss: 'his' },
  f: { subj: 'she', obj: 'her', poss: 'her' },
  n: { subj: 'it', obj: 'it', poss: 'its' },
  p: { subj: 'they', obj: 'them', poss: 'their' },
});

// createReaderModel — the theory-of-mind thread: a mirror of the reader's coref field,
// maintained by the writer so it can predict what the reader will resolve. It is NOT the
// writer's intent (the writer always knows which entity it means); it is the writer's
// model of the reader's resolution, kept on its own thread.
export const createReaderModel = ({ gamma = 0.7, warmFloor = 0.35, margin = 1.25 } = {}) => {
  const field = new Map();   // id → { salience, gender, name }
  const decay = () => { for (const v of field.values()) v.salience *= gamma; };

  return {
    field,
    // Would a pronoun for E resolve, in the reader's field, BACK to E? Only if E is the
    // most-salient gender-compatible candidate by a clear margin and warm enough.
    resolvesTo(id, gender) {
      const compat = [...field.entries()].filter(([, v]) => v.gender === gender);
      if (!compat.length) return false;
      compat.sort((a, b) => b[1].salience - a[1].salience);
      const [topId, top] = compat[0];
      if (topId !== id) return false;                          // a same-gender distractor is warmer → ambiguous
      if (top.salience < warmFloor) return false;              // E not active enough to pronominalise
      const next = compat[1];
      return !next || top.salience >= next.salience * margin;  // clear of the runner-up
    },
    // deposit a fresh mention of E (it is now the most recent), after decaying the rest.
    note(id, gender, name) { decay(); const v = field.get(id) || { salience: 0, gender, name }; v.salience += 1; v.gender = gender; v.name = name; field.set(id, v); },
    snapshot() { return [...field.entries()].map(([id, v]) => ({ id, salience: Math.round(v.salience * 1e3) / 1e3, gender: v.gender })).sort((a, b) => b.salience - a.salience); },
  };
};

// writeReferring(plan, opts) → { text, units, given, self }
//
//   plan   ordered propositions: { subj:{id,gender,name}, verb, obj?:{id,gender,name}|string }
//          (the meaning — typically read off a parsed doc, so the entities are real and
//          coref-resolved; that input is PERCEIVER-provenance, not-mine).
//
// Each clause is generated by inverse coref (the reader model decides pronoun vs name)
// and stamped ENACTOR-provenance (me-ness). The reader model is consulted BEFORE the
// referent is deposited, so the pronoun choice reflects the field the reader has at that
// moment — writing as reading backwards. `units` carry their provenance; `self` is the
// read-back of the generated units, recognised as mine.
export const writeReferring = (plan, { gamma = 0.7, enactment = 'voice', given = null } = {}) => {
  const reader = createReaderModel({ gamma });
  // Pronominalisation is a defeasible grammar rule: emit a pronoun only while it keeps
  // reading back to the meant entity. Each pronominalisable mention is an EVA — resolvable
  // in the reader's field → HOLD, ambiguous → BREAK. Enough breaks (a text thick with
  // same-gender referents) DEFEAT the rule and the writer turns cautious, using names.
  const pronRule = createRule();
  const units = [];
  const refer = (ent, role) => {
    if (!ent || ent.id == null) return typeof ent === 'string' ? ent : (ent?.name || '');
    // Pronominalise ONLY a gender the reading actually evidenced (m/f/p). An entity with no
    // gender evidence is referred to by NAME — never a fabricated "it", which is the writing
    // side of the same discipline reading uses: do not emit a referring form the reader
    // cannot license back to the meant entity.
    const evidenced = ent.gender === 'm' || ent.gender === 'f' || ent.gender === 'p';
    const pron = evidenced ? PRONOUN[ent.gender]?.[role] : null;
    const resolvable = !!pron && reader.resolvesTo(ent.id, ent.gender);
    if (pron) (resolvable ? pronRule.hold() : pronRule.break());   // EVA: read the choice back
    const usePronoun = pron && pronRule.on && resolvable;          // suppressed once the rule defeats
    // Determiner DERIVED from givenness (Gundel's hierarchy), not a hand-rule: a common-noun
    // referent the reader has already met is DEFINITE ("the"), a fresh one INDEFINITE ("a").
    // We read givenness off the reader's own field — measured state, closed-class scaffold
    // only. Proper names (capitalised) and pronouns take no determiner, so the default
    // (proper-named) telling is byte-identical; only catalyst-admitted common nouns get one.
    const given = reader.field.has(ent.id);
    const surface = usePronoun ? pron : determine(ent.name, given);
    reader.note(ent.id, ent.gender, ent.name);               // now E is the most recent
    return { surface, form: usePronoun ? 'pronoun' : 'name', id: ent.id, fieldAfter: reader.snapshot() };
  };

  for (const p of plan) {
    const s = refer(p.subj, 'subj');
    const o = p.obj && p.obj.id != null ? refer(p.obj, 'obj') : null;
    // Only a catalyst-vetted common-noun ENTITY (with an id) takes a derived determiner; a
    // bare np-string object is left alone — it may be a mass noun ("milk"), a plural, or a
    // mis-parse the reanalysis will fix ("fell"), none of which take an indefinite article.
    const objText = o ? o.surface : (typeof p.obj === 'string' ? p.obj : '');
    // verbs are realised in the narrative past (morph.js) — the source hands a bare/gerund
    // via when it stripped an auxiliary ("would accept" → "accept"); an already-past form is
    // kept. A reduced-relative modifier (from reanalysis): the relativizer is DERIVED from
    // animacy — "who" for an evidenced person (m/f/p), "that" otherwise — the only scaffold.
    const verb = toPast(p.verb);
    const relText = p.relative
      ? `, ${(p.subj.gender === 'm' || p.subj.gender === 'f' || p.subj.gender === 'p') ? 'who' : 'that'} ${toPast(p.relative.verb)},`
      : '';
    const text = `${cap(s.surface)}${relText} ${verb}${objText ? ' ' + objText : ''}.`;
    units.push(Object.freeze({
      text, subjForm: s.form, objForm: o?.form ?? null,
      // me-ness: the writer's own output enters through the ENACTOR door.
      prov: fromEnactor(enactment), mine: true,
      readerField: s.fieldAfter,
      // the recomposable pieces — so a grammatical-encoding stage (realize.js) can join
      // adjacent same-subject clauses without re-deciding the referring forms.
      parts: Object.freeze({ subjId: p.subj.id, subj: s.surface, verb, obj: objText, relText }),
    }));
  }

  return {
    text: units.map(u => u.text).join(' '),
    units,
    // the given content (if supplied) is PERCEIVER-provenance — it can witness, it is not mine.
    given: given ? { prov: fromPerceiver(), canWitness: canWitness(fromPerceiver()), mine: isMine(fromPerceiver()) } : null,
    // reading the generated units BACK (reenter through the perceiver door) — recognised
    // as READ_BACK-of-prior-self, still mine. The reafference loop that produces the self.
    self: units.map(u => { const rb = reenter(u.prov, { door: 'perceiver' }); return { text: u.text, mine: isMine(rb), readBackOfSelf: isReadBackOfPriorSelf(rb), canWitness: canWitness(rb) }; }),
  };
};

const cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s);

// Attach a determiner DERIVED from givenness, but only to a common-noun referent — a
// lowercase-initial head (proper names are capitalised; the common-noun catalyst lowercases).
// Given → definite "the"; new singular → indefinite "a/an"; new plural → bare (English has no
// indefinite plural article). Closed-class scaffold only; the choice is the reader's measured
// givenness, not a hand-rule. A name/pronoun/already-determined phrase passes through unchanged.
const determine = (noun, given) => {
  if (typeof noun !== 'string' || !/^[a-z]/.test(noun) || /^(the|a|an|his|her|its|their|my|your)\b/.test(noun)) return noun;
  if (given) return `the ${noun}`;
  if (/[^s]s$|[^aeiou]s$/.test(noun) && !/ss$/.test(noun)) return noun;   // plural → bare when new
  return `${/^[aeiou]/i.test(noun) ? 'an' : 'a'} ${noun}`;
};
