// The EO contract registry — every module in the tree, spelled on all three faces.
// A projection of the per-holon manifests (src/<holon>/eo-contract.js), merged into one
// path -> contract map. This is the conformance surface: tests/contracts.test.js reads it
// to prove 100% coverage and cube coherence. See docs/eo-for-coders.md (Law 1).
import { CONTRACTS as answer } from '../enactor/answer/eo-contract.js';
import { CONTRACTS as arc } from '../weave/arc/eo-contract.js';
import { CONTRACTS as attest } from '../attest/eo-contract.js';
import { CONTRACTS as binvis } from '../surfaces/binvis/eo-contract.js';
import { CONTRACTS as archive } from '../rooms/archive/eo-contract.js';
import { CONTRACTS as audit } from '../rooms/audit/eo-contract.js';
import { CONTRACTS as chat } from '../rooms/chat/eo-contract.js';
import { CONTRACTS as chorus } from '../weave/chorus/eo-contract.js';
import { CONTRACTS as classify } from '../perceiver/classify/eo-contract.js';
import { CONTRACTS as code } from '../organs/code/eo-contract.js';
import { CONTRACTS as codeHolons } from '../perceiver/code/eo-contract.js';
import { CONTRACTS as coder } from '../coder/eo-contract.js';
import { CONTRACTS as commission } from '../weave/commission/eo-contract.js';
import { CONTRACTS as connect } from '../enactor/connect/eo-contract.js';
import { CONTRACTS as converse } from '../turn/converse/eo-contract.js';
import { CONTRACTS as competencies } from '../rooms/competencies/eo-contract.js';
import { CONTRACTS as core_ } from './eo-contract.js';
import { CONTRACTS as credence } from '../perceiver/credence/eo-contract.js';
import { CONTRACTS as dag } from '../surfer/dag/eo-contract.js';
import { CONTRACTS as data } from '../rooms/data/eo-contract.js';
import { CONTRACTS as doc } from '../rooms/doc/eo-contract.js';
import { CONTRACTS as enact } from '../enactor/enact/eo-contract.js';
import { CONTRACTS as enactor } from '../enactor/eo-contract.js';
import { CONTRACTS as essay } from '../weave/essay/eo-contract.js';
import { CONTRACTS as factcheck } from '../enactor/factcheck/eo-contract.js';
import { CONTRACTS as flow } from '../surfer/flow/eo-contract.js';
import { CONTRACTS as fold } from '../surfer/fold/eo-contract.js';
import { CONTRACTS as frame } from '../frame/eo-contract.js';
import { CONTRACTS as generateRow } from '../weave/generate-row/eo-contract.js';
import { CONTRACTS as generation } from '../rooms/generation/eo-contract.js';
import { CONTRACTS as ground } from '../enactor/ground/eo-contract.js';
import { CONTRACTS as ingest } from '../organs/ingest/eo-contract.js';
import { CONTRACTS as lineup } from '../surfer/lineup/eo-contract.js';
import { CONTRACTS as longgen } from '../weave/longgen/eo-contract.js';
import { CONTRACTS as metabolism } from '../metabolism/eo-contract.js';
import { CONTRACTS as model } from '../model/eo-contract.js';
import { CONTRACTS as models } from '../rooms/models/eo-contract.js';
import { CONTRACTS as murmur } from '../murmur/eo-contract.js';
import { CONTRACTS as murmurAudit } from '../murmur/audit/eo-contract.js';
import { CONTRACTS as murmurLearn } from '../murmur/learn/eo-contract.js';
import { CONTRACTS as murmurLink } from '../murmur/link/eo-contract.js';
import { CONTRACTS as murmurNarrate } from '../murmur/narrate/eo-contract.js';
import { CONTRACTS as murmurSense } from '../murmur/sense/eo-contract.js';
import { CONTRACTS as murmurSteer } from '../murmur/steer/eo-contract.js';
import { CONTRACTS as murmurValence } from '../murmur/valence/eo-contract.js';
import { CONTRACTS as operatorClock } from '../surfaces/operator-clock/eo-contract.js';
import { CONTRACTS as organs } from '../organs/eo-contract.js';
import { CONTRACTS as perceiver } from '../perceiver/eo-contract.js';
import { CONTRACTS as predict } from '../perceiver/predict/eo-contract.js';
import { CONTRACTS as rawtext } from '../surfaces/rawtext/eo-contract.js';
import { CONTRACTS as reader } from '../rooms/reader/eo-contract.js';
import { CONTRACTS as reason } from '../surfer/reason/eo-contract.js';
import { CONTRACTS as render } from '../rooms/render/eo-contract.js';
import { CONTRACTS as replay } from '../rooms/replay/eo-contract.js';
import { CONTRACTS as research } from '../rooms/research/eo-contract.js';
import { CONTRACTS as retrieve } from '../surfer/retrieve/eo-contract.js';
import { CONTRACTS as scrubber } from '../rooms/scrubber/eo-contract.js';
import { CONTRACTS as store } from '../store/eo-contract.js';
import { CONTRACTS as surfaces } from '../surfaces/waveform/eo-contract.js';
import { CONTRACTS as surfer } from '../surfer/eo-contract.js';
import { CONTRACTS as tasks } from '../frame/tasks/eo-contract.js';
import { CONTRACTS as terrains } from '../rooms/terrains/eo-contract.js';
import { CONTRACTS as topline } from '../weave/topline/eo-contract.js';
import { CONTRACTS as turn } from '../turn/eo-contract.js';
import { CONTRACTS as waveform } from '../weave/waveform/eo-contract.js';
import { CONTRACTS as wiki } from '../wiki/eo-contract.js';
import { CONTRACTS as workspace } from '../rooms/workspace/eo-contract.js';
import { CONTRACTS as write } from '../weave/write/eo-contract.js';

export const CONTRACTS = Object.freeze({ ...answer, ...arc, ...attest, ...binvis, ...archive, ...audit, ...chat, ...chorus, ...classify, ...code, ...codeHolons, ...coder, ...commission, ...connect, ...converse, ...competencies, ...core_, ...credence, ...dag, ...data, ...doc, ...enact, ...enactor, ...essay, ...factcheck, ...flow, ...fold, ...frame, ...generateRow, ...generation, ...ground, ...ingest, ...lineup, ...longgen, ...metabolism, ...model, ...models, ...murmur, ...murmurAudit, ...murmurLearn, ...murmurLink, ...murmurNarrate, ...murmurSense, ...murmurSteer, ...murmurValence, ...operatorClock, ...organs, ...perceiver, ...predict, ...rawtext, ...reader, ...reason, ...render, ...replay, ...research, ...retrieve, ...scrubber, ...store, ...surfaces, ...surfer, ...tasks, ...terrains, ...topline, ...turn, ...waveform, ...wiki, ...workspace, ...write });

export const contractOf = (repoRelPath) => CONTRACTS[repoRelPath] ?? null;
export const contractedPaths = () => Object.freeze(Object.keys(CONTRACTS).sort());
