// EO: CON(Network → Link, Binding) — the declared cross-holon seams
// The seam registry — every import that reaches PAST a holon's entrance, declared.
//
// The holon law (docs/holons.md, docs/architecture.md) is one entrance: outside a
// holon's boundary only its index.js is visible. The kernel's stance on crossings
// (docs/eo-for-coders.md §7.5, core/contract.js) is that a crossing is legal but
// must be DECLARED — the sin was crossing silently. This registry applies that
// stance to the import graph: each pair below is a deep import that exists today,
// held visible so tests/boundaries.test.js can prove (a) no UNDECLARED crossing
// ever lands, and (b) no declared seam goes stale. Some seams are load-bearing by
// design — the hot retrieval path imports parse/tokenize directly so it carries no
// transitive dependency on the embedder or the model (docs/holons.md) — and the
// rest are the refactor's open worklist: heal a seam by routing it through the
// holon's entrance, then DELETE its row here (the orphan check enforces the
// deletion). The registry may only shrink; growing it is a design decision, made
// in review, never a silent side effect.
export const SEAMS = Object.freeze([
  ['src/coder/checkpoint.js', 'src/core/contract.js'],
  ['src/coder/checkpoint.js', 'src/core/cube.js'],
  ['src/coder/mask.js', 'src/core/contract.js'],
  ['src/coder/mask.js', 'src/core/cube.js'],
  ['src/coder/mask.js', 'src/core/operators.js'],
  ['src/coder/repair.js', 'src/core/contract.js'],
  ['src/coder/repair.js', 'src/core/cube.js'],
  ['src/coder/repair.js', 'src/core/operators.js'],
  ['src/enactor/connect/promote.js', 'src/core/provenance.js'],
  ['src/enactor/connect/promote.js', 'src/enactor/factcheck/correspond.js'],
  ['src/enactor/connect/promote.js', 'src/surfer/fold/deep-reading.js'],
  ['src/enactor/enact/meaning.js', 'src/perceiver/parse/clause-layer.js'],
  ['src/enactor/enact/stance-fold.js', 'src/core/enacted/stance.js'],
  ['src/enactor/factcheck/propositions.js', 'src/enactor/props.js'],
  ['src/enactor/ground/corroboration.js', 'src/core/witness.js'],
  ['src/enactor/ground/reflect.js', 'src/core/witness.js'],
  ['src/enactor/ground/validate.js', 'src/model/speak.js'],
  ['src/enactor/ground/validate.js', 'src/weave/chorus/born.js'],
  ['src/enactor/ledger.js', 'src/core/supersede.js'],
  ['src/frame/bind.js', 'src/weave/longgen/relax.js'],
  ['src/frame/conversation-fold.js', 'src/perceiver/parse/tokenize.js'],
  ['src/frame/tasks/constants.js', 'src/frame/constants.js'],
  ['src/frame/tasks/events.js', 'src/frame/events.js'],
  ['src/frame/tasks/grain.js', 'src/frame/grain.js'],
  ['src/frame/tasks/learn.js', 'src/perceiver/predict/segment.js'],
  ['src/frame/tasks/node.js', 'src/frame/node.js'],
  ['src/frame/tasks/project.js', 'src/frame/project.js'],
  ['src/metabolism/constitution.js', 'src/core/contract.js'],
  ['src/metabolism/constitution.js', 'src/core/cube.js'],
  ['src/metabolism/constitution.js', 'src/core/operators.js'],
  ['src/metabolism/def-oracle.js', 'src/core/verdicts.js'],
  ['src/metabolism/defharness.js', 'src/model/embed-hash.js'],
  ['src/metabolism/defharness.js', 'src/turn/pipeline.js'],
  ['src/metabolism/defscore.js', 'src/core/cut.js'],
  ['src/metabolism/defscore.js', 'src/core/def.js'],
  ['src/metabolism/defscore.js', 'src/core/verdicts.js'],
  ['src/metabolism/foresight.js', 'src/core/surprise.js'],
  ['src/metabolism/organ.js', 'src/core/contract.js'],
  ['src/metabolism/organ.js', 'src/core/cube.js'],
  ['src/metabolism/organ.js', 'src/core/holon.js'],
  ['src/metabolism/organ.js', 'src/core/operators.js'],
  ['src/metabolism/soma.js', 'src/core/cube.js'],
  ['src/model/blind-structure.js', 'src/organs/ingest/eot.js'],
  ['src/model/blind-structure.js', 'src/weave/write/redact.js'],
  ['src/model/prompt-checkpoint.js', 'src/core/voidnull.js'],
  ['src/murmur/learn/index.js', 'src/core/provenance.js'],
  ['src/murmur/learn/index.js', 'src/core/surprise.js'],
  ['src/murmur/link/index.js', 'src/core/provenance.js'],
  ['src/organs/code/compose.js', 'src/organs/ingest/eot.js'],
  ['src/organs/code/eot.js', 'src/organs/ingest/eot-emit.js'],
  ['src/organs/code/eot.js', 'src/organs/ingest/eot.js'],
  ['src/organs/code/helix.js', 'src/core/contract.js'],
  ['src/organs/code/page.js', 'src/core/holon.js'],
  ['src/organs/code/page.js', 'src/organs/ingest/eot.js'],
  ['src/organs/code/read.js', 'src/organs/ingest/eot.js'],
  ['src/organs/code/widget.js', 'src/organs/ingest/eot.js'],
  ['src/organs/in/code.js', 'src/organs/ingest/eot-emit.js'],
  ['src/organs/in/code.js', 'src/organs/ingest/eot.js'],
  ['src/organs/in/warc.js', 'src/organs/ingest/websource.js'],
  ['src/perceiver/predict/grained.js', 'src/surfer/sequence.js'],
  ['src/perceiver/predict/segment.js', 'src/surfer/sequence.js'],
  ['src/perceiver/referent-nesting.js', 'src/core/holon.js'],
  ['src/rooms/archive/checkpoints.js', 'src/organs/ingest/websource.js'],
  ['src/rooms/archive/pin.js', 'src/organs/ingest/websource.js'],
  ['src/rooms/archive/room-vault.js', 'src/rooms/chat/opfs-store.js'],
  ['src/rooms/archive/vault.js', 'src/rooms/chat/opfs-store.js'],
  ['src/rooms/data/query.js', 'src/enactor/answer/math.js'],
  ['src/rooms/doc/revise.js', 'src/surfer/salience.js'],
  ['src/rooms/plain/terrain.js', 'src/core/cube.js'],
  ['src/rooms/plain/terrain.js', 'src/core/operators.js'],
  ['src/rooms/reader/app.js', 'src/enactor/ground/spans.js'],
  ['src/rooms/reader/app.js', 'src/enactor/ledger.js'],
  ['src/rooms/reader/app.js', 'src/enactor/monitor.js'],
  ['src/rooms/reader/app.js', 'src/model/interface.js'],
  ['src/rooms/reader/app.js', 'src/model/reach.js'],
  ['src/rooms/reader/app.js', 'src/model/redact-remote.js'],
  ['src/rooms/reader/app.js', 'src/organs/in/composite.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/direct-cors.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/eot-emit.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/github.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/gutenberg.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/libraries.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/read.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/webfetch.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/websource.js'],
  ['src/rooms/reader/app.js', 'src/organs/ingest/wikimedia.js'],
  ['src/rooms/reader/app.js', 'src/rooms/archive/file-crypto.js'],
  ['src/rooms/reader/app.js', 'src/surfer/fold/deep-reading.js'],
  ['src/rooms/reader/app.js', 'src/surfer/levels.js'],
  ['src/rooms/reader/app.js', 'src/turn/nav-pool.js'],
  ['src/rooms/reader/app.js', 'src/turn/sense.js'],
  ['src/rooms/reader/app.js', 'src/turn/shape-grammar.js'],
  ['src/rooms/reader/app.js', 'src/weave/write/morph.js'],
  ['src/rooms/reader/eo-gen.js', 'src/enactor/ground/reflect.js'],
  ['src/rooms/reader/eo-gen.js', 'src/enactor/ground/spans.js'],
  ['src/rooms/reader/eo/chorus.js', 'src/core/operators.js'],
  ['src/rooms/reader/eo/chorus.js', 'src/weave/chorus/marginals.js'],
  ['src/rooms/reader/eo/chorus.js', 'src/weave/chorus/render.js'],
  ['src/rooms/reader/eo/vision.js', 'src/organs/ingest/opfs-store.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/anthropic.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/coders.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/coders.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/echo.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/interface.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/openai-local.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/prompt.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/stream.js'],
  ['src/rooms/reader/model-entry.js', 'src/model/webllm.js'],
  ['src/rooms/reader/monologue-surface.js', 'src/organs/in/text.js'],
  ['src/rooms/reader/reading-surface.js', 'src/organs/in/text.js'],
  ['src/rooms/reader/tiered-graph.js', 'src/surfer/fold/time-axis.js'],
  ['src/rooms/reader/wiki-referent.js', 'src/organs/ingest/wikimedia.js'],
  ['src/rooms/research/driver.js', 'src/core/cube.js'],
  ['src/rooms/research/driver.js', 'src/core/enacted/loop.js'],
  ['src/rooms/research/driver.js', 'src/core/operators.js'],
  ['src/rooms/research/driver.js', 'src/frame/constants.js'],
  ['src/rooms/research/driver.js', 'src/organs/ingest/websource.js'],
  ['src/rooms/research/driver.js', 'src/surfer/answerable.js'],
  ['src/rooms/research/driver.js', 'src/turn/research.js'],
  ['src/rooms/research/live.js', 'src/core/operators.js'],
  ['src/rooms/research/project.js', 'src/core/cube.js'],
  ['src/rooms/research/project.js', 'src/core/operators.js'],
  ['src/rooms/research/render.js', 'src/core/operators.js'],
  ['src/rooms/research/surface.js', 'src/turn/disambiguate.js'],
  ['src/store/database.js', 'src/core/project.js'],
  ['src/store/persistent-log.js', 'src/core/log.js'],
  ['src/surfer/answer.js', 'src/perceiver/surfaces.js'],
  ['src/surfer/fold/dispatch.js', 'src/core/voidnull.js'],
  ['src/surfer/lineup/index.js', 'src/core/log.js'],
  ['src/surfer/lineup/temperaments.js', 'src/core/surprise.js'],
  ['src/surfer/metacognition.js', 'src/perceiver/surfaces.js'],
  ['src/surfer/reason/cursor.js', 'src/core/provenance.js'],
  ['src/surfer/reason/cursor.js', 'src/surfer/dag/stance.js'],
  ['src/surfer/reason/walk.js', 'src/core/event.js'],
  ['src/surfer/reason/walk.js', 'src/core/provenance.js'],
  ['src/surfer/reason/walk.js', 'src/core/surprise.js'],
  ['src/surfer/salience.js', 'src/core/surprise.js'],
  ['src/turn/converse/reference.js', 'src/perceiver/parse/pipeline.js'],
  ['src/turn/deep-research.js', 'src/model/speak.js'],
  ['src/turn/deep-research.js', 'src/surfer/salience.js'],
  ['src/turn/depicted.js', 'src/perceiver/parse/pipeline.js'],
  ['src/turn/depicted.js', 'src/perceiver/predict/movelog.js'],
  ['src/turn/disambiguate.js', 'src/model/speak.js'],
  ['src/turn/disambiguate.js', 'src/perceiver/referent.js'],
  ['src/turn/expect.js', 'src/enactor/ground/veto.js'],
  ['src/turn/intent.js', 'src/core/voidnull.js'],
  ['src/turn/intent.js', 'src/surfer/salience.js'],
  ['src/turn/intent.js', 'src/weave/longgen/relax.js'],
  ['src/turn/judgments.js', 'src/core/cut.js'],
  ['src/turn/judgments.js', 'src/core/def.js'],
  ['src/turn/judgments.js', 'src/core/verdicts.js'],
  ['src/turn/meta-route.js', 'src/core/voidnull.js'],
  ['src/turn/meta-route.js', 'src/model/speak.js'],
  ['src/turn/meta-route.js', 'src/surfer/salience.js'],
  ['src/turn/meta-route.js', 'src/weave/longgen/relax.js'],
  ['src/turn/pipeline.js', 'src/core/def.js'],
  ['src/turn/pipeline.js', 'src/enactor/ground/reflect.js'],
  ['src/turn/pipeline.js', 'src/enactor/selfline.js'],
  ['src/turn/pipeline.js', 'src/model/interface.js'],
  ['src/turn/research.js', 'src/core/surprise.js'],
  ['src/turn/research.js', 'src/surfer/salience.js'],
  ['src/turn/stage-faces.js', 'src/core/cube.js'],
  ['src/turn/stage-faces.js', 'src/core/faces.js'],
  ['src/turn/stage-faces.js', 'src/core/operators.js'],
  ['src/turn/stages.js', 'src/rooms/data/query.js'],
  ['src/turn/stages.js', 'src/weave/longgen/answerable.js'],
  ['src/turn/stages.js', 'src/weave/write/concept-tokens.js'],
  ['src/turn/stages.js', 'src/weave/write/gravity.js'],
  ['src/turn/stages.js', 'src/weave/write/voice.js'],
  ['src/turn/web.js', 'src/model/speak.js'],
  ['src/weave/essay/driver.js', 'src/enactor/ground/bind.js'],
  ['src/weave/essay/driver.js', 'src/enactor/ground/section.js'],
  ['src/weave/essay/driver.js', 'src/model/speak.js'],
  ['src/weave/essay/driver.js', 'src/weave/arc/generate.js'],
  ['src/weave/longgen/confine.js', 'src/core/address.js'],
  ['src/weave/longgen/continuation.js', 'src/turn/converse/history.js'],
  ['src/weave/longgen/direction.js', 'src/perceiver/predict/movelog.js'],
  ['src/weave/longgen/direction.js', 'src/perceiver/predict/predictor.js'],
  ['src/weave/longgen/fold.js', 'src/model/speak.js'],
  ['src/weave/longgen/index.js', 'src/surfer/flow/select.js'],
  ['src/weave/longgen/relax.js', 'src/perceiver/predict/movelog.js'],
  ['src/weave/longgen/shape.js', 'src/perceiver/predict/movelog.js'],
  ['src/weave/longgen/walk.js', 'src/surfer/fold/deep-reading.js'],
  ['src/weave/topline/surface.js', 'src/core/contract.js'],
  ['src/weave/topline/surface.js', 'src/model/interface.js'],
  ['src/weave/write/cursor.js', 'src/model/prompt.js'],
  ['src/weave/write/folds.js', 'src/core/holder.js'],
  ['src/weave/write/folds.js', 'src/core/provenance.js'],
  ['src/weave/write/frame.js', 'src/perceiver/classify/bands.js'],
  ['src/weave/write/morph.js', 'src/core/conventions/english-verbs.js'],
  ['src/weave/write/paragraphs.js', 'src/surfer/salience.js'],
  ['src/weave/write/redact.js', 'src/organs/ingest/eot-emit.js'],
  ['src/wiki/render.js', 'src/core/operators.js'],
  ['src/wiki/spine.js', 'src/core/operators.js'],
  ['src/wiki/terrains.js', 'src/core/cube.js'],
].map(Object.freeze));

// The seam set, keyed "from → to", for the boundary test's membership check.
export const seamKey = (from, to) => `${from} → ${to}`;
export const SEAM_SET = Object.freeze(new Set(SEAMS.map(([f, t]) => seamKey(f, t))));
